apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d2arrows
  title: d2arrows
  description: A package containing python clients for communicating with various DII systems
spec:
  type: library
  lifecycle: experimental
  owner: group:default/data-analysis
